BOT_API_TOKEN = 
GOD 
GROUP = 
CHANNEL = 

MAX_ERR = 5

GOOGLE_DRIVE_ROOT_ID = ''
OD_CLIENT_ID = 
OD_CLIENT_SECERT = 
ONEDRIVE_ID = ''

QBIT_HOST = 'http://localhost:8080/'
QBIT_USR = 
QBIT_PWD = 
DOWNLOAD_MAX_SIZE = 21_474_836_480
TORRENT_TIMEOUT = 3600
TORRENT_ADJUST_THRESHOLD = 70

PRINT_EXC = True
TINEZONE_DELTA = {'hours': 8}

RCLONE_CONFIG = 
PROXY= None
LOCK_FILE = 'lock.pid'
